//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSections.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionImage
    {
        public int Section_id { get; set; }
        public byte[] Image_Data { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
